config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => ENV['MACURL']
  root 'home#index'
  match 'mac', to: 'mac#index', via: 'get', as: 'mac_index'
  match 'mymac', to: 'mac#personal', via: 'get', as: 'personal_mac_index'
  match 'mac/new', to: 'mac#new', via: 'get', as: 'new_mac'
  match 'mac/create', to: 'mac#create', via: 'post', as: 'create_mac'
  match 'mac/:id', to: 'mac#details', via: 'get', as: 'mac_details'
  match 'mac/:id/edit', to: 'mac#edit', via: 'get', as: 'edit_mac'
  match 'mac/:id/approve', to: 'mac#approve', via: 'get', as: 'approve_mac'
  match 'mac/:id/deny', to: 'mac#deny', via: 'post', as: 'deny_mac'
  match 'mac/:id/change', to: 'mac#change', via: 'patch', as: 'change_mac'
  match 'mac/:id/delete', to: 'mac#delete', via: 'delete', as: 'delete_mac'
  match 'mac/:id/comment', to: 'mac#createcomment', via: 'post', as: 'create_comment'
  match 'mac/:id/succeeded', to: 'mac#succeeded', via: 'post', as: 'succeeded_mac'
  match 'mac/:id/failed', to: 'mac#failed', via: 'post', as: 'failed_mac'
  match 'api', to: 'mac#api', via: 'get', as: 'mac_api'
  match 'mac/myapi', to: 'mac#personal_api', via: 'post', as: 'personal_mac_api'
  match 'analytics', to: 'analytics#index', via: 'get', as: 'analytics'
  match 'email', to: 'home#email', via: 'get', as: 'add_email'
  match 'email', to: 'home#emailsave', via: 'post', as: 'save_email'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :mac
end

app/models/division.rb
class Division < ActiveRecord::Base
end

app/models/mac.rb
class Mac < ActiveRecord::Base
  has_many :comment
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
    @macsbyday = Mac.group_by_day(:created_at).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !session[:email].nil? then redirect_to mac_index_path end
  end
  
  def email
  end
  
  def emailsave
    flash[:notice] = "Successfully saved your email address"
    session[:email] = params[:email][:address].downcase
    return redirect_to mac_index_path
  end
end

app/controllers/mac_controller.rb
class MacController < ApplicationController
  before_filter :require_email
  def index
  end

  def new
    @request = Mac.new
  end
  
  def personal
    @maccount = Mac.where(:requester => session[:email]).count
  end
  
  def create
    @mac = Mac.new(mac_params)
    @mac[:requester] = session[:email]
    @mac[:status] = "new"
    if @mac.save
      Newmacemail.new_request_email(session[:email], @mac.division, @mac.what, @mac.why, @mac.when, @mac.how, @mac.success, @mac.rollback, @mac.id).deliver_now
      flash[:notice] = "Successfully added MAC ID: #{@mac.id}"
      return redirect_to mac_index_path
    else
      flash[:alert] = "Failed to generate new MAC"
      return redirect_to new_mac_path
    end
  end
  
  def details
    @mac = Mac.find_by_id(params[:id])
    @comments = @mac.comment.all
  end
  
  def approve
    @mac = Mac.find_by_id(params[:id])
    @mac.status = "approved"
    if @mac.save
      Newmacemail.approve_request_email(session[:email], @mac.id).deliver_now
      flash[:notice] = "Successfully approved MAC ID: #{@mac.id}"
      return redirect_to  mac_index_path
    else
      flash[:alert] = "Failed to update MAC"
      return redirect_to  mac_details_path(params[:id])
    end
  end
  
  def deny
    @mac = Mac.find_by_id(params[:id])
    @mac.status = "denied"
    @mac.reason = params[:mac][:reason]
    if @mac.save
      Newmacemail.deny_request_email(session[:email], @mac.id, @mac.reason).deliver_now
      flash[:notice] = "Successfully denied MAC ID: #{@mac.id}"
      return redirect_to  mac_index_path
    else
      flash[:alert] = "Failed to update MAC"
      return redirect_to  mac_details_path(params[:id])
    end
  end
  
  def succeeded
    @mac = Mac.find_by_id(params[:id])
    @mac.status = "succeeded"
    @mac.successreason = params[:mac][:successreason]
    if @mac.save
      Newmacemail.succeeded_request_email(session[:email], @mac.id, @mac.successreason).deliver_now
      flash[:notice] = "MAC ID: #{@mac.id} SUCCEEDED"
      return redirect_to mac_index_path
    else
      flash[:alert] = "Failed to update MAC"
      return redirect_to  mac_details_path(params[:id])
    end
    
  end
  
  def failed
    @mac = Mac.find_by_id(params[:id])
    @mac.status = "failed"
    @mac.failreason = params[:mac][:failreason]
    if @mac.save
      Newmacemail.failed_request_email(session[:email], @mac.id, @mac.failreason).deliver_now
      flash[:notice] = "MAC ID: #{@mac.id} FAILED to implement"
      return redirect_to mac_index_path
    else
      flash[:alert] = "Failed to update MAC"
      return redirect_to  mac_details_path(params[:id])
    end
    
  end
  
  def createcomment
    @mac = Mac.find(params[:id])
    @comment = @mac.comment.create(comment_params)
    if @comment.save
      Newmacemail.new_comment_email(session[:email], @mac.id, @comment.content).deliver_now
      flash[:notice] = "Successfully added comment to MAC ID: #{@mac.id}"
      return redirect_to mac_details_path(params[:id])
    else
      flash[:alert] = "Failed to add your comment"
      return redirect_to mac_details_path(params[:id])
    end
  end
  
  def edit
    @mac = Mac.find(params[:id])
    if @mac.requester != session[:email]
      flash[:alert] = "You do not have permissions to edit this MAC"
      return redirect_to mac_index_path
    end
  end
  
  def change
    @mac = Mac.find(params[:id])
    if @mac.update_attributes(mac_params)
      Newmacemail.edit_request_email(session[:email], @mac.division, @mac.what, @mac.why, @mac.when, @mac.how, @mac.success, @mac.rollback, @mac.id).deliver_now
      flash[:success] = "MAC Updated"
      return redirect_to mac_details_path(params[:id])
    else
      flash[:alert] = "Failed to update MAC"
      render 'edit'
end
  end
  
  def delete
  end
  
  def api
    @macs = Mac.all.pluck(:id, :division, :what, :when, :status, :requester)
    @data = {"data": @macs}
    return render :json => @data.to_json
  end
  
  def personal_api
    @macs = Mac.where(:requester => params[:email]).pluck(:id, :division, :what, :when, :status)
    @data = {"data": @macs}
    return render :json => @data.to_json
  end
  
  private 
  
  def require_email
    if !session[:email] then redirect_to add_email_path end
  end
  
  def mac_params
    params.require(:mac).permit(:division, :what, :why, :when, :how, :success, :rollback, :requester, :status, :successreason, :failreason, :reason)
  end
    
  def comment_params
    params.require(:comment).permit(:saidby, :content)
  end
  
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # for nice notifications with toastr
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      puts type

      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mac_helper.rb
module MacHelper
end

app/views/analytics/_allmacsgraph.html.erb
<div class="allmacs-margin">
<div class="row">
    <div class="col-sm-12">
        <h4 align="center">All MAC requests submitted in the last week</h4>
        <div id="allmacscontainer" style="height: 350px;">
        </div>
    </div>
</div>
</div>
<script type="text/javascript">
  //set the javascript variables for the graph before its rendered
  var allmacslabels = [<% @macsbyday.each do |x| %> "<%= x.first.to_s %>", <% end %>]
  var allmacsdata = [<% @macsbyday.each do |x| %> "<%= x.second.to_s %>", <% end %>]
  //render the big line graph in the canvas tag
  allmacsgraph(allmacslabels, allmacsdata);
</script>

app/views/analytics/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-primary newpanel">
      <div class="panel-body newpanel-body">
        <%= render partial: 'analytics/allmacsgraph' %>
      </div>
    </div>
  </div>
</div>

app/views/home/email.html.erb
<% @body_id = "home" %>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default emailpanel">
      <div class="panel-body emailpanel-body">
        <h1 align="center">Add/Edit your current email address</h1>
        <hr/>
        <div align="center">
          <br/>
          <%= form_for :email, url: save_email_path, method: :post, html: { class: "form-inline", id: "" } do |f| %>
            <%= f.text_field :address, placeholder: "Email address", value: "#{session[:email]}", class: 'form-control', style: "width: 70%", :required => true  %>
            <%= f.submit "Save", class: "btn btn-primary" %>
          <% end %>
          <br/>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% @body_id = "home" %>
<div class="row">
  <div class="panel panel-default homepagepanel">
    <div class="panel-body homepagepanel-body">
      <h1 align="center">Holtec MAC Request Form</h1>
      <br/><hr/>
      <div align="center">
        <br/>
        <%= link_to "Create a new request", new_mac_path, class: 'btn btn-lg btn-success' %>
        <br/><br/>
        <hr/>
        <%= link_to "Browse existing requests", mac_index_path, class: 'btn btn-default' %>
        <%= link_to "Analytics", analytics_path, class: 'btn btn-default' %> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="menu">
  <div class="container">
    <div class="navbar-header">
  		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
  			<span class="sr-only">Toggle navigation</span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  		</button>
      <% if !session[:email] %>
        <%= link_to root_url, class: "navbar-brand" do %>
          <b>IT MAC Change Form</b>
        <% end %>
      <% else %>
        <%= link_to mac_index_path, class: "navbar-brand" do %>
          <b>IT MAC Change Form</b>
        <% end %>
      <% end %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "New Request", new_mac_path %></li>
            <li><%= link_to "My Requests", personal_mac_index_path %></li>
            <li><%= link_to "Browse", mac_index_path %></li>
            <li><%= link_to "Analytics", analytics_path %></li>
            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  Options
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Add/Edit Email", add_email_path %></li>
                </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_nprogress.html.erb
<script>
$(document).on('turbolinks:click', function() {
  NProgress.start();
});
$(document).on('turbolinks:render', function() {
  NProgress.done();
  NProgress.remove();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>IT MAC Change Form</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.png"/>
</head>
<body <%= "id=#{@body_id}" if @body_id %>>
    <div class="container">
        <%= render partial: 'layouts/header' %>
        <%= render partial: 'layouts/nprogress' %>
        <% if notice or alert %>
          <%= custom_bootstrap_flash %>
        <% end %>
        <%= yield %>
    </div>
</body>
</html>

app/views/mac/details.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-primary newpanel">
      <div class="panel-heading" align="center">
        <b>Details for MAC #<%=params[:id]%></b>
        <% if session[:email] == @mac.requester and @mac.status != "approved" and @mac.status != "succeeded" and @mac.status != "failed" %><%= link_to "Edit", edit_mac_path(params[:id]), class: "btn btn-default", style: "float: right; margin-top: -6px;" %><% end %>
        <% if session[:email] == @mac.requester and @mac.status == "approved" and @mac.status != "succeeded" and @mac.status != "failed"  %><button class="btn btn-success" style="float: right; margin-top: -6px;" type="button" data-toggle="collapse" href="#collapseSuccess" aria-expanded="false" aria-controls="collapseSuccess">Succeeded</button><% end %>
        <% if session[:email] == @mac.requester and @mac.status == "approved" and @mac.status != "succeeded" and @mac.status != "failed"  %><button class="btn btn-warning" style="float: left; margin-top: -6px;" type="button" data-toggle="collapse" href="#collapseFailed" aria-expanded="false" aria-controls="collapseFailed">Failed</button><% end %>
        <% if session[:email] != @mac.requester and @mac.status != "succeeded" and @mac.status != "failed"  %><%= link_to "Approve", approve_mac_path(params[:id]), class: "btn btn-success", style: "float: right; margin-top: -6px;margin-left: -75px;" %><% end %>
        <% if session[:email] != @mac.requester and @mac.status != "succeeded" and @mac.status != "failed"  %><button class="btn btn-warning" style="float: left; margin-top: -6px;" type="button" data-toggle="collapse" href="#collapseDeny" aria-expanded="false" aria-controls="collapseDeny">Deny</button><% end %>
      </div>
      <div class="panel-body newpanel-body">
        <div class="collapse" id="collapseSuccess">
          <div class="well">
            <%= form_for :mac, url: succeeded_mac_path(params[:id]), method: :post, html: { class: "", id: "" } do |f| %>
              <div class="form-group">
                <%= f.label :successreason, "Enter any success notes you may have", style: 'color: #333' %>
                <%= f.text_field :successreason, placeholder: "Enter any success notes you may have...", class: 'form-control'  %>
              </div>
              <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
        </div>
        <div class="collapse" id="collapseFailed">
          <div class="well">
            <%= form_for :mac, url: failed_mac_path(params[:id]), method: :post, html: { class: "", id: "" } do |f| %>
              <div class="form-group">
                <%= f.label :failreason, "Enter a reason for the change failure", style: 'color: #333' %>
                <%= f.text_field :failreason, placeholder: "Reason for MAC rollback/failure...", class: 'form-control'  %>
              </div>
              <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
        </div>
        <div class="collapse" id="collapseDeny">
          <div class="well">
            <%= form_for :mac, url: deny_mac_path(params[:id]), method: :post, html: { class: "", id: "" } do |f| %>
              <div class="form-group">
                <%= f.label :reason, "Enter reason for MAC request denial", style: 'color: #333' %>
                <%= f.text_field :reason, placeholder: "Your denial reason...", class: 'form-control'  %>
              </div>
              <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
        </div>
        <table class="table">
          <tr>
            <td style="border-top: none;"><b>Requested by: </b></td>
            <td style="border-top: none;"><%= @mac.requester %></td>
          </tr>
          <tr>
            <td><b>Status: </b></td>
            <td><%= @mac.status %></td>
          </tr>
          <tr>
            <td><b>For Division: </b></td>
            <td><%= @mac.division %></td>
          </tr>
          <tr>
            <td><b>What: </b></td>
            <td><%= @mac.what %></td>
          </tr>
          <tr>
            <td><b>Why: </b></td>
            <td><%= @mac.why %></td>
          </tr>
          <tr>
            <td><b>When: </b></td>
            <td><%= @mac.when %></td>
          </tr>
          <tr>
            <td><b>How: </b></td>
            <td><%= @mac.how %></td>
          </tr>
          <tr>
            <td><b>Success: </b></td>
            <td><%= @mac.success %></td>
          </tr>
          <tr>
            <td><b>Rollback: </b></td>
            <td><%= @mac.rollback %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-primary newpanel">
      <div class="panel-heading" align="center">
        <b>Comments </b>
        <button class="btn btn-default" style="float: right; margin-top: -6px;" type="button" data-toggle="collapse" href="#collapseComment" aria-expanded="false" aria-controls="collapseComment">
          Add Comment
        </button>
      </div>
      <div class="panel-body newpanel-body">
        <div class="collapse" id="collapseComment">
          <div class="well">
            <%= form_for @mac.comment.build, url: create_comment_path(params[:id]), method: :post, html: { class: "", id: "" } do |f| %>
              <%= f.hidden_field :saidby, :value => session[:email] %>
              <div class="form-group">
                <%= f.label :content, "Enter your comment", style: 'color: #333' %>
                <%= f.text_field :content, placeholder: "Your comment...", class: 'form-control', :required => true  %>
              </div>
              <%= f.submit "Add comment", class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
        </div>
        <% if @comments.empty? %>
        <div align="center">
          <b>No Comments.</b>
        </div>
        <% else %>
            <table class="table">
              <thead>
              <th>Commenter</th>
              <th>Comment</th>
              </thead>
              <tbody>
                <% @comments.reverse.each do |x| %>
                    <tr>
                      <td><b><%= x.saidby %></b> <small><%= time_ago_in_words(x.created_at) %> ago</small></td>
                      <td><%= x.content %></td>
                    </tr>
                <% end %>
              </tbody>
            </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mac/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-primary newpanel">
      <div class="panel-heading" align="center">
        <b>Editing MAC request <%= link_to mac_details_path(params[:id]), style: "color: #ccc" do %>#<%=@mac.id%><% end %></b>
      </div>
      <div class="panel-body newpanel-body">
        <div>
          <%= form_for @mac, url: change_mac_path(params[:id]), method: :patch, html: { class: "", id: "" } do |f| %>
          <%= f.hidden_field :status, :value => "Updated" %>
          <div class="form-group">
            <%= f.label :division, "Which division will this change take place in?" %>
            <%= f.select :division, options_for_select(Division.pluck(:name), @mac.division), {}, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :what, "What change are you making?" %>
            <%= f.text_field :what, placeholder: "What", class: 'form-control', :required => true  %>
          </div>
          <div class="form-group">
            <%= f.label :why, "Why are you making this change?" %>
            <%= f.text_area :why, placeholder: "Why", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :when, "When will this change take place?" %>
            <%= f.text_field :when, placeholder: "When", class: 'form-control', :required => true  %>
          </div>
          <div class="form-group">
            <%= f.label :how, "How will you implement your change?" %>
            <%= f.text_area :how, placeholder: "How", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :success, "What will this acheive on success?" %>
            <%= f.text_area :success, placeholder: "Success", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :rollback, "What is the rollback plan if this fails?" %>
            <%= f.text_area :rollback, placeholder: "Rollback", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <%= f.submit "Update MAC request", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br/>

app/views/mac/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-primary newpanel">
      <div class="panel-heading" align="center">
        <b>Browse all requests</b>
      </div>
      <div class="panel-body newpanel-body">
        <table id="maclist" class="table table-bordered table-hover" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>Division</th>
              <th>What</th>
              <th>When</th>
              <th>Status</th>
              <th>Requester</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function() {
  if (<%= Mac.count %> > 0) {
  var mactable = $('#maclist').dataTable( {
  "order": [[ 0, "desc" ]],
  "bDeferRender": true,
  "ajax": {
    "url": "/api.json",
    "type": "GET"
  }
} );
 $( "#maclist" ).on( "click", 'tbody tr', function() {
   window.location.href = "/mac/"+$(this).children("td:first").text();
} );
  };
} );
</script>

app/views/mac/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-primary newpanel">
      <div class="panel-heading" align="center">
        <b>New request form</b>
      </div>
      <div class="panel-body newpanel-body">
        <div>
          <%= form_for @request, url: create_mac_path, method: :post, html: { class: "", id: "" } do |f| %>
          <div class="form-group">
            <%= f.label :division, "Which division will this change take place in?" %>
            <%= f.select :division, options_for_select(Division.pluck(:name)), {include_blank: "Select A Division"}, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :what, "What change are you making?" %>
            <%= f.text_field :what, placeholder: "What", class: 'form-control', :required => true  %>
          </div>
          <div class="form-group">
            <%= f.label :why, "Why are you making this change?" %>
            <%= f.text_area :why, placeholder: "Why", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :when, "When will this change take place?" %>
            <%= f.text_field :when, placeholder: "When", class: 'form-control', :required => true  %>
          </div>
          <div class="form-group">
            <%= f.label :how, "How will you implement your change?" %>
            <%= f.text_area :how, placeholder: "How", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :success, "What will this acheive on success?" %>
            <%= f.text_area :success, placeholder: "Success", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :rollback, "What is the rollback plan if this fails?" %>
            <%= f.text_area :rollback, placeholder: "Rollback", class: 'form-control', :rows => 2, :required => true %>
          </div>
          <%= f.submit "Submit new MAC request", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br/>

app/views/mac/personal.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-primary newpanel">
      <div class="panel-heading" align="center">
        <b>Your requests</b>
      </div>
      <div class="panel-body newpanel-body">
        <table id="maclist" class="table table-bordered table-hover" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>Division</th>
              <th>What</th>
              <th>When</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function() {
  if (<%= @maccount %> > 0) {
  var myemail = {email:"<%=session[:email]%>"};
  var mactable = $('#maclist').dataTable( {
  "order": [[ 0, "desc" ]],
  "bDeferRender": true,
  "ajax": {
    "type": "POST",
    "url": "/mac/myapi.json",
    "data": myemail
  }
} );
 $( "#maclist" ).on( "click", 'tbody tr', function() {
   window.location.href = "/mac/"+$(this).children("td:first").text();
} );
  };
} );
</script>

app/views/newmacemail/approve_request_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>Request approved for MAC <%= @id %></h2>
    <p><b>Approved by:</b> <%= @email %></p>
  </body>
</html>

app/views/newmacemail/deny_request_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>Request denied for MAC <%= @id %></h2>
    <p><b>Denied by:</b> <%= @email %><br/>
    Reason: </b><%= @reason %></p>
  </body>
</html>

app/views/newmacemail/edit_request_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>MAC request <%=@id %> has been revised</h2>
    <p><b>For Division:</b> <%= @division %><br/>
    <b>Status: </b>Updated<br/>
    <b>What: </b><%=@what %><br/>
    <b>Why: </b><%=@why %><br/>
    <b>When: </b><%=@when %><br/>
    <b>How: </b><%=@how %><br/>
    <b>Success: </b><%=@success %><br/>
    <b>Rollback: </b><%=@rollback %></p>
  </body>
</html>

app/views/newmacemail/failed_request_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>MAC <%= @id %></h2>
    <p><b>Flagged as failed to make change by:</b> <%= @email %><br/>
    <b>Reason for failure/rollback: </b><%= @reason %></p>
  </body>
</html>

app/views/newmacemail/new_comment_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>A new comment has been added for MAC <%= @id %></h2>
    <p><b>Comment by:</b> <%= @email %><br/>
    <b>Comment: </b><%= @content %></p>
  </body>
</html>

app/views/newmacemail/new_request_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>New MAC request <%=@id %> submitted</h2>
    <p><b>For Division:</b> <%= @division %><br/>
    <b>Status: </b>New<br/>
    <b>What: </b><%=@what %><br/>
    <b>Why: </b><%=@why %><br/>
    <b>When: </b><%=@when %><br/>
    <b>How: </b><%=@how %><br/>
    <b>Success: </b><%=@success %><br/>
    <b>Rollback: </b><%=@rollback %><br/></p>
  </body>
</html>

app/views/newmacemail/succeeded_request_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body align="center">
    <h2>MAC <%= @id %></h2>
    <p><b>Successfully implemented by:</b> <%= @email %><br/>
    <b>Success notes: </b><%= @reason %></p>
  </body>
</html>